version: "3.8"
services:
  db:
    image: mysql:8
    container_name: laundry_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laundrydb
      MYSQL_USER: team_user
      MYSQL_PASSWORD: team_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: laundry_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/laundrydb
      SPRING_DATASOURCE_USERNAME: team_user
      SPRING_DATASOURCE_PASSWORD: team_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db_data:
